export {
  TH_FIRST_MESSAGE,
  TH_PRONUNCIATION_LOCK,
  TH_SPOKEN_COMPANY,
  TH_SPOKEN_FOUNDER,
  TH_SPOKEN_SUNNY,
  TH_TTS_REPLACEMENTS,
  TH_VOICE_CHUNK_PLAN,
} from '../../vapi/pronunciation.mjs';
